### ISSUE TITLE
SeleniumTest > b_testSendTitle FAILED org.openqa.selenium.WebDriverException: unknown error: INVALID_STATE_ERR

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#23]
@edewit FYI our split (#14) `SeleniumTest` _still_ sometimes fails for me locally, despite #17.

actually the cause perhaps it's not even the split - it may be machine load related. I just hit below while running it during a boring call :smile: while a BlueJeans was taking up some CPU, and when re-running after BJ ended, it passed.

```
> Task :web:test 

ch.vorburger.minecraft.storeys.web.SeleniumTest > a_testBasicSetUp PASSED

ch.vorburger.minecraft.storeys.web.SeleniumTest > b_testSendTitle FAILED
    org.openqa.selenium.WebDriverException: unknown error: INVALID_STATE_ERR
```

**Comment by edewit** [comment]
might be that the wait is not long enough if the machine is under stress, we need a better solution then waiting for this `INVALID_STATE_ERR`

**Comment by vorburger** [comment]
@edewit yeah... although this actually isn't even on a  `FluentWait<WebDriver>` but it's the `JavascriptExecutor.executeScript` that is causing this; see below. This actually happens on and off locally to me as well, today it was not while BlueJeans was running, but with minishift in the background... and it went away after I retried. Perhaps moving entirely away from `JavascriptExecutor.executeScript` and just letting a JS Test framework do everything, with clicking on buttons, and `FluentWait<WebDriver>` to await some grey bar becoming green or red, based on your https://github.com/vorburger/minecraft-storeys-maker/pull/21, is the way to go here.

**Comment by vorburger** [comment]
https://github.com/vorburger/minecraft-storeys-maker/pull/95 from @edewit will also fix this problem, I suspect.
