### ISSUE TITLE
Missing documentation how to use Scratch integration

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#270]
For #259 I'm trying to remember 😈 what was what how and I'm actually struggling myself...

If one does a `docker run` as per https://github.com/OASIS-learn-study/minecraft-storeys-maker#dockerfile, do we need to set the  `storeys_jsURL` and `storeys_eventBusURL` with an `-e`?

How much of what https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/scratch/README.md described is still relevant, and could be summarized succinctly on the main README for container, and what should be cleaned-up there?

Where was the Scratch UI again - I'm getting a _"Resource not found"_ on http://localhost:8080.

@edewit help? 🥲

**Comment by edewit** [comment]
right `storeys_jsURL` is old it should be `storeys_gui` (default localhost:7070/index.html) and `storeys_eventBusURL` (localhost:8080)

**Comment by vorburger** [comment]
@edewit I've just retried it, following https://github.com/OASIS-learn-study/minecraft-storeys-maker#dockerfile, but `/make` (=  
`/scratch`) gives me _You don't have permission to use this command!_ I can't remember how to fix that... 😈  (Also what was `/login` for again?)

**Comment by vorburger** [comment]
I have it working again locally now, so closing this, all good.
