### ISSUE TITLE
Container (Dockerfile) must support persistance

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#275]
Running it with a volume e.g. like this:

    docker run -it --rm -v $HOME/Minecraft:/data:Z \
        -e OPS=73551f35-7acb-45c0-bc65-8083c53eec69 -p 25565:25565 -p 8080:8080 -p 7070:7070 minecraft-storeys-maker

currently "breaks" this - because the Storeys Sponge plugins which [the Dockerfile](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/Dockerfile) copies to `/data/mods/` are "hidden" (lost).

@edewit FYI

**Comment by vorburger** [comment]
According to https://github.com/itzg/docker-minecraft-server#working-with-mods-and-plugins, perhaps putting them into `/plugins` (or `/mods` ?) could do the trick here.

**Comment by edewit** [comment]
yes `/mods` is synchronised to `/data/mods` so that should work
