### ISSUE TITLE
Clarify minecraft-storeys* NPM packages

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#290]
@edewit where is the source code of https://www.npmjs.com/package/minecraft-storeys-scratch-vm which this repo [currently seems to use](https://github.com/OASIS-learn-study/minecraft-storeys-maker/search?q=minecraft-storeys-scratch-vm), [here](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/a9c17c8cd7f26b8293d1c04a53bdd941c9776b07/scratch3-server/scratch-server.js#L6) and [here](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/b4313dbba4824bd1ee3c965ebee887572adaeac7/scratch3-server/package.json#L16)?

Dito for the other related packages on https://www.npmjs.com/search?q=minecraft-storeys ... which of these is what? 

https://www.npmjs.com/package/minecraft-storeys = https://github.com/OASIS-learn-study/minecraft-storeys-maker/tree/develop/api? The Versions tabs shows that it was downloaded twice in the last 7 days. Does this mean when we build this project it fetches that from NPM? Shouldn't (couldn't) it use the local version built from this repo instead? Could it be removed from NPM, to avoid confusion?

minecraft-storeys-scratch-gui is used by [scratch3/package.json](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/b5135b0ec820c1bfe0de611df187e5aac303c828/scratch3/package.json) but I don't really understand where that's from.

minecraft-storeys-scratch3-server is from `scratch3-server/` here, and used in [web/src/main/resources/package.json](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/a9c17c8cd7f26b8293d1c04a53bdd941c9776b07/web/src/main/resources/package.json) it seems, according to [this search](https://github.com/OASIS-learn-study/minecraft-storeys-maker/search?q=minecraft-storeys-scratch3-server).

Or is all this about to disappear with what you are hacking on for #50? (Asking because you mentioned that "we won't need a fork of Scratch anymore".)

**Comment by edewit** [comment]
The `minecraft-storeys-scratch-vm` is [located here](https://github.com/edewit/scratch-vm/tree/storeys) it's a fork of the scratch-vm with added an extension for minecraft storeys. I also have a fork of the [GUI project](https://github.com/edewit/scratch-gui/tree/storeys) that adds a screen special for for storeys that can load and save scratch projects on our minecraft server.

To list everything:
1. [minecraft-storeys](https://www.npmjs.com/package/minecraft-storeys)
   * This is the javascript API to talk with the vertx event bus what is used in [test.js](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/minecraft-server-test-data/config/storeys-web/scripts/test.js)
1. [minecraft-storeys-scratch-vm](https://www.npmjs.com/package/minecraft-storeys-scratch-vm)
   * Is the scratch-vm with the minecraft storeys extension added that uses minecraft-storeys to communicate
1. [minecraft-storeys-scratch-gui](https://www.npmjs.com/package/minecraft-storeys-scratch-gui)
   * Is the gui that uses the `minecraft-storeys-scratch-vm `and adds a screen to be able to save load projects.
1. [minecraft-storeys-scratch3-server](https://www.npmjs.com/package/minecraft-storeys-scratch3-server)
  * Is a server that loads javascript and scratch projects and runs them in the background it uses  `minecraft-storeys-scratch-vm` and `minecraft-storeys` to do this.

**Comment by vorburger** [comment]
[docs/architecture.md](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/docs/architecture.md) (from #314) references this.
