### ISSUE TITLE
Fully automated end2end testing

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#327]
It could be fun if our (new, introduced yesterday) [manual testing steps](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/docs/testing.md) could be fully automated.

This would be possible with [a programmatic Minecraft client](https://wiki.vg/Client_List) , such as:

* https://github.com/willemml/hl-mc-kt (unmaintained, take over?)
* https://github.com/PrismarineJS/mineflayer (JS)
* https://github.com/Defective4/Another-Minecraft-Chat-Client (part of, refactor)
* https://gitlab.bixilon.de/bixilon/minosoft (part of, refactor)

https://github.com/GeyserMC/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java looks great, but is too low level. Ask them if they know of any higher level libs built on them?

**Comment by vorburger** [comment]
We concluded that https://github.com/PrismarineJS/mineflayer is the way to go here! The (future) "test" then doesn't need Java, nor [TestContainers](https://www.testcontainers.org/), nor [JBang](https://www.jbang.dev) - we'll just add 1 line to `./test` which launches `node run mineflayer` (or whatever). (Later split off a new `./start` [only] called by `./test`.)

**Comment by vorburger** [comment]
#348 made a start for this. What's left:

1. Run Mineflayer test on CI, instead of just running `Dockerfile` for each PR; see #355 et al.
1. factor out a `start` & `stop` from `test`
1. moar tests (if possible?)

**Comment by vorburger** [comment]
1. will be taken care of in #381 + #375 + #382

2. doesn't seem that important anymore (to me)

3. is what we should still do ASAP... the current test just makes sure a Minecraft user can login, but doesn't actually test any of our plugin's functionality; the current test as-is would still pass as long as the server started, even if our plugin was completely broken. The goal here should be to automate at least some sort of subset of what we are describing in [our Testing doc](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/docs/testing.md).

**Comment by vorburger** [comment]
@edewit I just thought about this again... especially with #375 now done, which will then enable #382, it would be REALLY cool if we could slightly beef up our Mineflyer based test to do something a bit more interesting than only login - anything that could test our plugin loaded and works. That could give us the confidence among other things e.g. to approve Dependabot PRs, among other things, if we see them pass the build, once that includes a more useful real test. If showing title and make entities narrate isn't something that we can easily test with Mineflyer, then let's add whatever else is needed to our test JS and/or Java that we can actually really test with Mineflyer? Have a go at it if you are up for it! 😸

**Comment by edewit** [comment]
Having entries narrate in a mineflyer test is not possible, but we would be able to get the chat, so let me add that

**Comment by vorburger** [comment]
#400 adds additional coverage.
