### ISSUE TITLE
Add Checkstyle for common code format conventions

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#334]
While reviewing @edewit #332 I noticed that we are undoing each others' `@Override` and `@Inject` same/next line code format convention.

In the short term, we can simply both agree here which convention we prefer, and manually set it to the same in our IDEs.

The "proper" fix would be to add proper Checkstyle to the project, some day.

**Comment by edewit** [comment]
I don't like the @Override and @Inject on the same line, but if you like it it's fine... I'll add some formatting rules

**Comment by vorburger** [comment]
> The "proper" fix would be to add proper Checkstyle to the project, some day.

The `checkstyle.xml` from [my MariaDB4j](https://github.com/vorburger/MariaDB4j/blob/master/checkstyle.xml) or [from OpenDaylight](https://github.com/opendaylight/odlparent/blob/master/checkstyle/src/main/resources/odl_checks.xml) or from [Apache Fineract](https://github.com/apache/fineract/blob/develop/config/checkstyle/checkstyle.xml), all which I'm responsible for, could be starting points for this project.

**Comment by vorburger** [comment]
> I don't like the @OverRide and @Inject on the same line, but if you like it it's fine... I'll add some formatting rules

I actually don't have very strong feelings either way, and find it's more important that we use the same, to make PRs have less diff. I'm happy to go "your" way if you want - it's probably more standard, in Java. I just like having them "inline" if there is only 1 becaues it makes code a bit more "dense" one line less. It's also what other languages who have an `override` keyword use.

**Comment by vorburger** [comment]
Particularly I find `@Test void comments()` more natural to read than `@Test \n void comments()`.

**Comment by vorburger** [comment]
We could also agree on the import statement ordering we prefer for this project...

@edewit are you cool with the "plain" (non traditionally "grouped") "modern" variant?

**Comment by vorburger** [comment]
In #322 I have a commit to _"Add Eclipse Preferences (and Formatter)"_ (currently a623e32ff1687556e1be3f9b98a1a1957e1d8ff5).

Let's agree our code format conventions for this project, and then put that commit on `develop`, as a start of this issue.

If there is an IntelliJ equivalent settings kind of things, you could contribute that as well. 

Maybe we could put all that, different IDE configs + later Checkstyle config, into a common place, say... `code-format/` ?

**Comment by vorburger** [comment]
This should bring back checking the `LICENSE-HEADER` against all files, which was lost in #344.
