### ISSUE TITLE
Template YAML to set this up on OpenShift (instead of README)

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#57]
instead of [the OpenShift section in the README](https://github.com/vorburger/minecraft-storeys-maker#build-it), we should have a Template YAML ([like this](https://github.com/edewit/minecraft-che-test/blob/master/.openshiftio/application.yaml)).

**Comment by vorburger** [comment]
@corinnekrych @edewit contributions for this most welcome! ;-)

**Comment by edewit** [comment]
@vorburger maybe instead of this crazy big yaml we could [kedge](http://kedgeproject.org/getting-started/)

**Comment by vorburger** [comment]
@edewit or https://github.com/ansibleplaybookbundle/ansible-playbook-bundle (not https://github.com/openshift/openshift-ansible), but that's probably overkill... :smile:
